module.exports = {
  preset: "ts-jest",
  setupFilesAfterEnv: ["@testing-library/jest-dom"],
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.[t]sx?$",
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  testEnvironment: "jsdom",
  collectCoverage: true,
  collectCoverageFrom: ["src/**/*.{ts,tsx}"],
  coveragePathIgnorePatterns: [
    "/build/",
    "/node_modules/",
    "<rootDir>/src/index.tsx",
    "<rootDir>/src/router/",
    "<rootDir>/src/@types/",
    "<rootDir>/src/services/",
    "<rootDir>/src/api/",
    "<rootDir>/src/utils/",
    "<rootDir>/src/constants/",
    "<rootDir>/src/styles/",
    ".*index\\.ts$",
    ".*styles\\.ts$",
  ],
  coverageReporters: ["lcov", "cobertura", "text", "clover"],
  reporters: [
    "default",
    [
      "jest-sonar",
      {
        outputDirectory: "report/sonar",
        outputName: "sonar-test-execution-report.xml",
        reportedFilePath: "absolute",
      },
    ],
  ],
};
