/**
 * @interface {Member}
 * @description Complete member entity interface
 * @property {string} id - Primary key generated by JSON-server or database system
 * @property {string} email - The email address of the member
 * @property {number[]} books - Array of book IDs associated with the member
 * @property {string} dateOfJoining - The date when the member joined
 * @property {string} avatar - Optional URL to the member's avatar image
 */
export interface Member {
  id?: string;
  email: string;
  books: number[];
  dateOfJoining: string;
  avatar?: string;
}

/**
 * @interface {MemberFormData}
 * @description Member form data interface for create/edit operations
 * @property {string} email - The email address of the member
 * @property {number[]} books - Array of book IDs associated with the member
 */
export interface MemberFormData {
  email: string;
  books: number[];
}
