/**
 * @fileoverview Member-related type definitions for the Reading Club application
 *
 * @version 1.0.0
 * @since 1.0.0
 */

/**
 * Complete member entity interface
 *
 * @interface Member
 * @property {string} id - Primary key generated by JSON-server or database system
 * @property {string} email - The email address of the member
 * @property {number[]} books - Array of book IDs associated with the member
 * @property {string} dateOfJoining - The date when the member joined
 * @property {string} avatar - Optional URL to the member's avatar image
 */
export interface Member {
  id?: string;
  email: string;
  books: number[];
  dateOfJoining: string;
  avatar?: string;
}

/**
 * Member form data interface for create/edit operations
 *
 * @interface MemberFormData
 * @property {string} email - The email address of the member
 * @property {number[]} books - Array of book IDs associated with the member
 */
export interface MemberFormData {
  email: string;
  books: number[];
}
